[project]
name = "core-models"
version = "0.1.0"
description = "Shared pydantic models and schemas"
requires-python = ">=3.11"
dependencies = ["pydantic>=2.7.0"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
