[build-system]
requires = ["setuptools>=65.5.1", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "core_http"
version = "0.1.0"
description = "Shared HTTP client with stage-aware timeouts and OTEL propagation"
requires-python = ">=3.11"
dependencies = [
  "httpx>=0.27.0",
  "orjson>=3.9.7",
  "core_config",
  "core_observability",
]

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["core_http"]

[tool.ruff]
line-length = 100