[project]
name = "core_observability"
version = "0.1.0"
description = "OpenTelemetry bootstrap + FastAPI middleware"
requires-python = ">=3.11"
dependencies = [
  "opentelemetry-api>=1.24",
  "opentelemetry-sdk>=1.24",
  "opentelemetry-exporter-otlp-proto-http>=1.24",
]

[project.optional-dependencies]
dev = [
  "pytest>=8.0",
  "pytest-asyncio>=0.23",
  "pytest-env>=0.8",
  "httpx>=0.27.0",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where  = ["src"]
include = ["core_observability*"]

[tool.ruff]
line-length = 100