name: ci
on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install package tooling
        run: |
          python -m pip install -U pip wheel setuptools
          pip install ruff pytest
      - name: Lint packages
        run: |
          ruff check packages || true
      - name: Python unit tests
        run: |
          pytest -q || true
